import type { NextPage } from "next"
import Head from "next/head"
import styles from "../styles/Home.module.css"

const Home: NextPage = () => (
  <div aria-label="cryptopunt." className="px-8">
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="min-h-screen py-16 flex-1 flex flex-col justify-center items-center">
      <h1 className={styles.title}>
        Welcome to <strong className="text-blue-500">Crypto punt.</strong>
      </h1>
    </main>
  </div>
)

export default Home
